import uuid
from datetime import datetime

from geoalchemy2 import Geography
from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship

from .database import Base


class User(Base):
    __tablename__ = "users"

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # Stable UUID generated by the client on first launch — no phone / password needed
    device_id = Column(String(36), unique=True, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    posts = relationship("Post", back_populates="user")
    votes = relationship("Vote", back_populates="user")


class Post(Base):
    __tablename__ = "posts"

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    content = Column(Text, nullable=False)
    # Geography type stores WGS-84 coordinates; ST_DWithin distances are in metres
    location = Column(Geography("POINT", srid=4326), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    user_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    parent_id = Column(PGUUID(as_uuid=True), ForeignKey("posts.id"), nullable=True)

    user = relationship("User", back_populates="posts")
    replies = relationship("Post", foreign_keys=[parent_id])
    votes = relationship("Vote", back_populates="post")


class Vote(Base):
    __tablename__ = "votes"
    __table_args__ = (UniqueConstraint("user_id", "post_id", name="uq_user_post_vote"),)

    id = Column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(PGUUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    post_id = Column(PGUUID(as_uuid=True), ForeignKey("posts.id"), nullable=False)
    value = Column(Integer, nullable=False)  # +1 or -1
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="votes")
    post = relationship("Post", back_populates="votes")
