# DigitalOcean App Platform spec
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/
#
# Deploy via:  doctl apps create --spec .do/app.yaml
# Update via:  doctl apps update <app-id> --spec .do/app.yaml

name: 216labs

services:
  - name: ramblingradio
    dockerfile_path: RamblingRadio/Dockerfile
    source_dir: /RamblingRadio
    github:
      repo: 6cubed/216labs
      branch: main
      deploy_on_push: true
    http_port: 5000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${ramblingradio-db.DATABASE_URL}
        scope: RUN_TIME

  - name: stroll
    dockerfile_path: Stroll.live/Dockerfile
    source_dir: /Stroll.live
    github:
      repo: 6cubed/216labs
      branch: main
      deploy_on_push: true
    http_port: 5000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production

  - name: onefit
    dockerfile_path: onefit/Dockerfile
    source_dir: /onefit
    github:
      repo: 6cubed/216labs
      branch: main
      deploy_on_push: true
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production

  - name: paperframe-frontend
    dockerfile_path: paperframe/frontend/Dockerfile
    source_dir: /paperframe/frontend
    github:
      repo: 6cubed/216labs
      branch: main
      deploy_on_push: true
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: ${paperframe-backend.PUBLIC_URL}
        scope: BUILD_TIME

  - name: paperframe-backend
    dockerfile_path: paperframe/backend/Dockerfile
    source_dir: /paperframe/backend
    github:
      repo: 6cubed/216labs
      branch: main
      deploy_on_push: true
    http_port: 8000
    instance_size_slug: professional-xs
    instance_count: 1
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: SAM_MODEL_TYPE
        value: vit_b
      - key: OMP_NUM_THREADS
        value: "1"

databases:
  - name: ramblingradio-db
    engine: PG
    version: "16"
    size: db-s-dev-database
    num_nodes: 1
