"""Curated seed places (Ireland) with one illustrative instant experience each.

Coordinates are approximate public points. Copy is illustrative — users should verify locally.
"""

SEED = [
    {
        "name": "Trinity College Dublin",
        "lat": 53.3438,
        "lon": -6.2546,
        "category": "attraction",
        "locality": "Dublin",
        "address": "College Green",
        "headline": "Walk the cobbles under the Campanile",
        "body": "Public paths through Front Square and the Library precinct — a classic Dublin stroll with centuries of student life in the air.",
        "kind": "walk",
    },
    {
        "name": "Guinness Storehouse",
        "lat": 53.3419,
        "lon": -6.2867,
        "category": "attraction",
        "locality": "Dublin",
        "address": "St James's Gate",
        "headline": "Gravity bar pint with city views",
        "body": "The headline Dublin visitor experience: learn the pour, then a pint overlooking the rooftops — the city's most famous glass of stout.",
        "kind": "drink",
    },
    {
        "name": "St Stephen's Green",
        "lat": 53.3379,
        "lon": -6.2590,
        "category": "park",
        "locality": "Dublin",
        "address": "St Stephen's Green",
        "headline": "Bench coffee in the Georgian heart",
        "body": "Grab a takeaway cappuccino nearby and people-watch by the lake — a calm break between Grafton Street and the museums.",
        "kind": "food",
    },
    {
        "name": "Grafton Street",
        "lat": 53.3425,
        "lon": -6.2597,
        "category": "public_space",
        "locality": "Dublin",
        "address": "Grafton Street",
        "headline": "Buskers and window-shopping stretch",
        "body": "The pedestrian mile: street music, Brown Thomas glow, and side-streets into cafés — Dublin's retail theatre.",
        "kind": "culture",
    },
    {
        "name": "Temple Bar",
        "lat": 53.3453,
        "lon": -6.2672,
        "category": "pub",
        "locality": "Dublin",
        "address": "Temple Bar",
        "headline": "Trad and pints in the tourist quarter",
        "body": "Cobbles, live music spilling from doorways, and the famous photo op — loud, proud, and unmistakably Dublin.",
        "kind": "drink",
    },
    {
        "name": "Phoenix Park",
        "lat": 53.3556,
        "lon": -6.3296,
        "category": "park",
        "locality": "Dublin",
        "address": "Phoenix Park",
        "headline": "Deer-spotting loop on foot or bike",
        "body": "One of Europe's largest city parks — wide avenues, herds of fallow deer, and the President's gardens at Áras an Uachtaráin nearby.",
        "kind": "walk",
    },
    {
        "name": "Howth Harbour",
        "lat": 53.3915,
        "lon": -6.0725,
        "category": "attraction",
        "locality": "Howth",
        "address": "Howth",
        "headline": "Cliff walk then fish and chips",
        "body": "Salt air, trawlers, and the loop trail above the sea — finish with takeaway seafood by the pier.",
        "kind": "food",
    },
    {
        "name": "Dún Laoghaire East Pier",
        "lat": 53.2939,
        "lon": -6.1358,
        "category": "walk",
        "locality": "Dún Laoghaire",
        "address": "Harbour Road",
        "headline": "Windy pier stroll at golden hour",
        "body": "Locals' favourite leg-stretch: ferries, sail masts, and ice cream kiosks — Dublin Bay laid out in panorama.",
        "kind": "walk",
    },
    {
        "name": "English Market, Cork",
        "lat": 51.9010,
        "lon": -8.4746,
        "category": "shop",
        "locality": "Cork",
        "address": "Princes St",
        "headline": "Cork's lunch cathedral",
        "body": "Covered stalls of cheese, fish, and spice — grab a sandwich upstairs or ingredients for a picnic by the Lee.",
        "kind": "food",
    },
    {
        "name": "Shandon Bells, Cork",
        "lat": 51.9032,
        "lon": -8.5102,
        "category": "attraction",
        "locality": "Cork",
        "address": "Shandon",
        "headline": "Climb and ring the bells",
        "body": "Iconic red-and-white tower — panoramic Cork and a hands-on bell session if you time it right.",
        "kind": "culture",
    },
    {
        "name": "Galway City Centre (Shop Street)",
        "lat": 53.2724,
        "lon": -9.0532,
        "category": "public_space",
        "locality": "Galway",
        "address": "Shop Street",
        "headline": "Buskers and Spanish Arch wander",
        "body": "Street energy, knit shops, then down to the Claddagh — the compact core of the west's festival city.",
        "kind": "culture",
    },
    {
        "name": "Salthill Promenade",
        "lat": 53.2604,
        "lon": -9.0714,
        "category": "walk",
        "locality": "Galway",
        "address": "Salthill",
        "headline": "Prom kick-the-wall tradition",
        "body": "Blackrock diving tower, mile of sea air, and the little ritual at the end of the prom — pure Galway weekend.",
        "kind": "walk",
    },
    {
        "name": "King John's Castle, Limerick",
        "lat": 52.6689,
        "lon": -8.6305,
        "category": "attraction",
        "locality": "Limerick",
        "address": "Nicholas St",
        "headline": "Shannon views from the battlements",
        "body": "Interactive castle museum where the river meets medieval Limerick — quick history hit before the Milk Market side of town.",
        "kind": "culture",
    },
    {
        "name": "Waterford Greenway (city access)",
        "lat": 52.2567,
        "lon": -7.1291,
        "category": "walk",
        "locality": "Waterford",
        "address": "Waterford",
        "headline": "Bike the old railway line",
        "body": "Hop on the Greenway for car-free kilometres of river and estuary — Ireland's favourite rail-trail escape.",
        "kind": "walk",
    },
    {
        "name": "Kilkenny Castle Park",
        "lat": 52.6506,
        "lon": -7.2492,
        "category": "attraction",
        "locality": "Kilkenny",
        "address": "The Parade",
        "headline": "Castle lawn picnic",
        "body": "Norman keep meets manicured park — free grounds, duck pond, and medieval lanes a minute away.",
        "kind": "walk",
    },
    {
        "name": "Killarney National Park (Muckross)",
        "lat": 52.0025,
        "lon": -9.5025,
        "category": "park",
        "locality": "Killarney",
        "address": "Muckross",
        "headline": "Jaunting car or lakeside ramble",
        "body": "Oak woods, lakeshore paths, and Torc Waterfall trails — the postcard Kerry nature fix.",
        "kind": "walk",
    },
    {
        "name": "Ross Castle, Killarney",
        "lat": 52.0412,
        "lon": -9.5356,
        "category": "attraction",
        "locality": "Killarney",
        "address": "Lough Leane",
        "headline": "Boat trip from the jetty",
        "body": "Tower house on the lake — combine a short cruise with a loop of the lower lakes for the full Killarney moment.",
        "kind": "culture",
    },
    {
        "name": "Titanic Belfast",
        "lat": 54.6080,
        "lon": -5.9044,
        "category": "attraction",
        "locality": "Belfast",
        "address": "Queens Road",
        "headline": "Shipyard story in aluminium shards",
        "body": "Museum architecture as iconic as the story — plan a couple of hours, then Titanic Quarter cafés.",
        "kind": "culture",
    },
    {
        "name": "St George's Market, Belfast",
        "lat": 54.5990,
        "lon": -5.9184,
        "category": "shop",
        "locality": "Belfast",
        "address": "East Bridge St",
        "headline": "Weekend food hall crawl",
        "body": "Victorian market hall with hot food, antiques, and live music — arrive hungry on Friday–Sunday.",
        "kind": "food",
    },
    {
        "name": "Giant's Causeway (visitor approach)",
        "lat": 55.2408,
        "lon": -6.5116,
        "category": "attraction",
        "locality": "County Antrim",
        "address": "Bushmills",
        "headline": "Hexagon stepping stones at the sea",
        "body": "UNESCO coastline — clifftop path down to the basalt columns; allow half a day with the visitor centre.",
        "kind": "walk",
    },
    {
        "name": "Slieve League Cliffs",
        "lat": 54.6379,
        "lon": -8.6808,
        "category": "attraction",
        "locality": "County Donegal",
        "address": "Teelin",
        "headline": "Higher than the Cliffs of Moher",
        "body": "Atlantic drop-offs in Donegal's gaeltacht — quieter drama and winding roads worth the trip.",
        "kind": "walk",
    },
    {
        "name": "Donegal Town centre",
        "lat": 54.6538,
        "lon": -8.1100,
        "category": "public_space",
        "locality": "Donegal",
        "address": "The Diamond",
        "headline": "Harbour town wander",
        "body": "Diamond junction, castle ruins nearby, and gateway to the northwest — stock up before the coastal loops.",
        "kind": "culture",
    },
    {
        "name": "Cliffs of Moher (visitor area)",
        "lat": 52.9719,
        "lon": -9.4267,
        "category": "attraction",
        "locality": "County Clare",
        "address": "Liscannor",
        "headline": "Atlantic breeze on the edge",
        "body": "Ireland's most photographed cliffs — paved paths, O'Brien's Tower, and seabirds on the updraft.",
        "kind": "walk",
    },
    {
        "name": "Dingle Harbour",
        "lat": 52.1409,
        "lon": -10.2695,
        "category": "attraction",
        "locality": "Dingle",
        "address": "Strand Street",
        "headline": "Fungie legacy boat trips",
        "body": "Colourful fishing town — seafood chowder, pubs with trad sessions, and bay cruises when the weather plays ball.",
        "kind": "food",
    },
    {
        "name": "Athlone town centre (Shannon)",
        "lat": 53.4239,
        "lon": -7.9406,
        "category": "public_space",
        "locality": "Athlone",
        "address": "Athlone",
        "headline": "River Shannon crossing coffee",
        "body": "Midland hub on the water — castle, bridges, and cafés before heading west or east on the M6 corridor.",
        "kind": "food",
    },
    {
        "name": "Sligo town (Garavogue)",
        "lat": 54.2697,
        "lon": -8.4694,
        "category": "public_space",
        "locality": "Sligo",
        "address": "Sligo",
        "headline": "Yeats country gateway",
        "body": "River walks, Benbulben on the horizon, and surf beaches a short drive — northwest character in one compact town.",
        "kind": "culture",
    },
    {
        "name": "Wexford Quay",
        "lat": 52.3369,
        "lon": -6.4633,
        "category": "walk",
        "locality": "Wexford",
        "address": "The Quay",
        "headline": "Harbour light stroll",
        "body": "Southeast sailing town — quayside pubs, opera festival pedigree, and strawberry season lore.",
        "kind": "drink",
    },
    {
        "name": "Drogheda (Boyne)",
        "lat": 53.7189,
        "lon": -6.3478,
        "category": "public_space",
        "locality": "Drogheda",
        "address": "Drogheda",
        "headline": "Boyne bridges and high crosses",
        "body": "Historic garrison town — Newgrange and Battle of the Boyne sites are day-trip close.",
        "kind": "culture",
    },
    {
        "name": "Bunratty Castle & Folk Park",
        "lat": 52.7677,
        "lon": -8.7822,
        "category": "attraction",
        "locality": "County Clare",
        "address": "Bunratty",
        "headline": "Medieval banquet night",
        "body": "Folk village, castle keep, and the famous evening feast — touristy in the best way near Shannon Airport.",
        "kind": "food",
    },
    {
        "name": "Cobh (Titanic last port)",
        "lat": 51.8503,
        "lon": -8.2947,
        "category": "attraction",
        "locality": "Cobh",
        "address": "Cobh",
        "headline": "Deck-of-cards houses on the hill",
        "body": "Steep streets above Cork Harbour — Titanic Experience, cathedral views, and ferries to Spike Island.",
        "kind": "culture",
    },
    {
        "name": "Kinsale harbour",
        "lat": 51.7077,
        "lon": -8.5210,
        "category": "restaurant",
        "locality": "Kinsale",
        "address": "Kinsale",
        "headline": "Gourmet capital seafood lunch",
        "body": "Ireland's foodie harbour — yacht masts, colourful shopfronts, and chowder trails along the waterfront.",
        "kind": "food",
    },
    {
        "name": "Tramore Beach",
        "lat": 52.1586,
        "lon": -7.0123,
        "category": "attraction",
        "locality": "Tramore",
        "address": "County Waterford",
        "headline": "Amusement pier and long beach",
        "body": "Classic Irish seaside — dunes, prom, and chips in paper when the Atlantic behaves.",
        "kind": "walk",
    },
    {
        "name": "Bray Seafront",
        "lat": 53.2028,
        "lon": -6.0986,
        "category": "walk",
        "locality": "Bray",
        "address": "County Wicklow",
        "headline": "Cliff walk from the prom",
        "body": "DART-accessible: pier, Bray Head path, and views back to Dublin Bay — weekend escape energy.",
        "kind": "walk",
    },
    {
        "name": "Glendalough Monastic Site",
        "lat": 53.0104,
        "lon": -6.3270,
        "category": "attraction",
        "locality": "County Wicklow",
        "address": "Glendalough",
        "headline": "Round tower between two lakes",
        "body": "Early medieval valley — short lakeside loops to full Wicklow Way sections; spiritual and cinematic.",
        "kind": "walk",
    },
    {
        "name": "Illustrative: Dublin specialty coffee (Capel St)",
        "lat": 53.3476,
        "lon": -6.2754,
        "category": "cafe",
        "locality": "Dublin",
        "address": "Capel Street area",
        "headline": "Third-wave espresso break",
        "body": "Capel Street's indie café strip — flat whites, natural wine bars nearby, and the Liffey a block south.",
        "kind": "food",
    },
    {
        "name": "Illustrative: Lebanese takeaway (Dublin north inner city)",
        "lat": 53.3521,
        "lon": -6.2625,
        "category": "restaurant",
        "locality": "Dublin",
        "address": "Parnell Street area",
        "headline": "Late-night shawarma run",
        "body": "Dublin's diverse food scene — charcoal kebabs and garlic sauce after a gig or theatre; check reviews for today's favourite spot.",
        "kind": "food",
    },
    {
        "name": "Illustrative: Independent health store (Ranelagh)",
        "lat": 53.3259,
        "lon": -6.2566,
        "category": "shop",
        "locality": "Dublin",
        "address": "Ranelagh village",
        "headline": "2-for-1 kombucha run (when listed)",
        "body": "Village grocers often run multi-buy deals on chilled drinks — peek at shelf tickets for fermented tea and snacks.",
        "kind": "deal",
    },
    {
        "name": "Illustrative: Historic pub (Dublin south)",
        "lat": 53.3352,
        "lon": -6.2655,
        "category": "pub",
        "locality": "Dublin",
        "address": "Portobello / Camden area",
        "headline": "Pint of plain near the canal",
        "body": "Grand Canal ambience — settle in for a slow pint; many locals still debate 'the best Guinness' by neighbourhood loyalty.",
        "kind": "drink",
    },
]
