# Illustrative seed rows — fictional companies for demo; replace with your own watchlist.
from __future__ import annotations

SEED: list[dict] = [
    {
        "name": "LatticeMind",
        "one_liner": "Edge inference for robotics OEMs",
        "sector": "AI / robotics",
        "stage": "Pre-seed",
        "valuation_usd": 6_500_000,
        "website_url": "https://example.com",
        "notes": "Two xooglers; SAFE at $8M cap discussed informally.",
        "signal_slugs": ["xoogler_founded", "technical_cofounder", "hot_sector"],
    },
    {
        "name": "Northbound DB",
        "one_liner": "Postgres-compatible OLAP for SaaS metrics",
        "sector": "Data infra",
        "stage": "Seed",
        "valuation_usd": 9_000_000,
        "website_url": "",
        "notes": "Sequoia scout intro; ex-Meta infra lead.",
        "signal_slugs": ["tier1_vc", "ex_faang", "hot_sector"],
    },
    {
        "name": "ParcelRelay",
        "one_liner": "B2B last-mile routing API",
        "sector": "Logistics",
        "stage": "Pre-seed",
        "valuation_usd": 4_000_000,
        "website_url": "",
        "notes": "YC W24; second-time founder (exited small e-com tool).",
        "signal_slugs": ["yc_batch", "repeat_founder", "accelerator"],
    },
    {
        "name": "HelioSketch",
        "one_liner": "AI layout copilot for CAD teams",
        "sector": "Dev tools",
        "stage": "Pre-seed",
        "valuation_usd": None,
        "website_url": "",
        "notes": "Valuation TBD — party round at $25k min.",
        "signal_slugs": ["xoogler_founded", "hot_sector"],
    },
    {
        "name": "Cedar Compliance",
        "one_liner": "EU AI Act readiness for mid-market",
        "sector": "Regtech",
        "stage": "Seed",
        "valuation_usd": 8_500_000,
        "website_url": "",
        "notes": "a16z speedrun participant; former Stripe PM.",
        "signal_slugs": ["accelerator", "tier1_vc", "repeat_founder"],
    },
    {
        "name": "QuietStack",
        "one_liner": "Noise-aware scheduling for open offices",
        "sector": "Productivity",
        "stage": "Pre-seed",
        "valuation_usd": 3_200_000,
        "website_url": "",
        "notes": "No brand-name signals yet — tracking for price.",
        "signal_slugs": [],
    },
]
