#!/usr/bin/env bash
# Plug-and-play local toolkit: env, admin auth, minimal Caddy, demo stack.
#
# Usage (from repo root):
#   ./scripts/bootstrap-toolkit.sh
#   ./scripts/bootstrap-toolkit.sh --no-up          # prepare only (no docker compose up)
#   ./scripts/bootstrap-toolkit.sh --starter-config # also copy toolkit deploy-*.txt examples
#
# After it finishes:
#   http://localhost/              landing
#   http://admin.localhost/        admin (basic auth — printed below)
#   http://hello-nextjs.localhost/ demo
#   http://hello-flask.localhost/  demo
#
# Modern macOS/Linux resolve *.localhost → 127.0.0.1 (no /etc/hosts edit).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

NO_UP=0
STARTER_CONFIG=0
for arg in "$@"; do
  case "$arg" in
    --no-up) NO_UP=1 ;;
    --starter-config) STARTER_CONFIG=1 ;;
    -h|--help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (try --help)" >&2
      exit 1
      ;;
  esac
done

ENV_TOOLKIT="$ROOT/.env.toolkit"
CREDS_FILE="$ROOT/.toolkit-admin-credentials"
CADDY_LOCAL="$ROOT/Caddyfile.local"
SERVICES=(caddy activator admin landing hello-nextjs hello-flask)

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: '$1' is required. Install it and re-run." >&2
    exit 1
  fi
}

need docker
need python3
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' (V2) is required." >&2
  exit 1
fi

DOCKER_OK=0
if docker info >/dev/null 2>&1; then
  DOCKER_OK=1
fi
if [[ "$NO_UP" -eq 0 && "$DOCKER_OK" -eq 0 ]]; then
  echo "ERROR: Docker daemon is not running. Start Docker Desktop (or dockerd) and re-run." >&2
  echo "       Or prepare files only: ./scripts/bootstrap-toolkit.sh --no-up" >&2
  exit 1
fi

echo "==> 216labs toolkit bootstrap"

# ── Credentials (reuse if present) ─────────────────────────────
ADMIN_USER="${ADMIN_USER:-admin}"
if [[ -f "$CREDS_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CREDS_FILE"
  echo "==> Reusing admin password from .toolkit-admin-credentials"
fi
if [[ -z "${ADMIN_PASSWORD:-}" ]]; then
  ADMIN_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(16))')"
fi

HASH=""
HASH_B64=""
if [[ "$DOCKER_OK" -eq 1 ]]; then
  echo "==> Hashing admin password (caddy:2-alpine)…"
  HASH="$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "$ADMIN_PASSWORD")"
  HASH_B64="$(printf '%s' "$HASH" | base64 | tr -d '\n')"
elif command -v htpasswd >/dev/null 2>&1; then
  echo "==> Hashing admin password (htpasswd -nbB)…"
  # htpasswd output: user:hash — take hash only
  HASH="$(htpasswd -nbB "$ADMIN_USER" "$ADMIN_PASSWORD" | cut -d: -f2-)"
  HASH_B64="$(printf '%s' "$HASH" | base64 | tr -d '\n')"
else
  echo "==> WARNING: Docker daemon down and no htpasswd — wrote password without hash." >&2
  echo "    Start Docker and re-run bootstrap before 'compose up' (admin auth needs the hash)." >&2
fi

# ── .env.toolkit (does not overwrite a production .env) ────────
CRON_SECRET="${CRON_RUNNER_SECRET:-}"
if [[ -z "$CRON_SECRET" ]]; then
  CRON_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"
fi

cat > "$ENV_TOOLKIT" <<EOF
# Generated by scripts/bootstrap-toolkit.sh — local toolkit only (gitignored).
# Production deploy keeps using .env + .env.admin on the droplet.
APP_HOST=localhost
COMPOSE_PROJECT_NAME=216labs
COMPOSE_PULL_POLICY=never
ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD_HASH_B64=${HASH_B64}
CRON_RUNNER_SECRET=${CRON_SECRET}
ACTIVATOR_PULL_BEFORE_COLD_START=false
ACTIVATOR_MAX_CONCURRENT_APPS=0
EOF

cat > "$CREDS_FILE" <<EOF
ADMIN_USER=${ADMIN_USER}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF
chmod 600 "$CREDS_FILE" "$ENV_TOOLKIT" 2>/dev/null || true

# Fresh clones: also create .env so other scripts see APP_HOST=localhost
if [[ ! -f "$ROOT/.env" ]]; then
  echo "==> Creating .env from .env.example (APP_HOST=localhost)"
  if [[ -f "$ROOT/.env.example" ]]; then
    cp "$ROOT/.env.example" "$ROOT/.env"
  else
    touch "$ROOT/.env"
  fi
  python3 - "$ROOT/.env" <<'PY'
import pathlib, re, sys
path = pathlib.Path(sys.argv[1])
text = path.read_text() if path.exists() else ""
def upsert(key: str, val: str) -> None:
    global text
    pat = re.compile(rf"^{re.escape(key)}=.*$", re.M)
    line = f"{key}={val}"
    if pat.search(text):
        text = pat.sub(line, text)
    else:
        text = (text.rstrip() + "\n" + line + "\n") if text.strip() else (line + "\n")
upsert("APP_HOST", "localhost")
path.write_text(text)
PY
  # Merge toolkit auth into .env for compose auto-load on fresh clones
  {
    echo ""
    echo "# --- toolkit bootstrap ---"
    grep -E '^(ADMIN_USER|ADMIN_PASSWORD_HASH_B64|CRON_RUNNER_SECRET|COMPOSE_PROJECT_NAME)=' "$ENV_TOOLKIT"
  } >> "$ROOT/.env"
fi

# Empty DB + admin env overlay (admin creates schema on first boot)
touch "$ROOT/216labs.db"
touch "$ROOT/.env.admin"

if [[ "$STARTER_CONFIG" -eq 1 ]]; then
  echo "==> Applying toolkit starter deploy config"
  "$ROOT/scripts/init-toolkit-starter-config.sh"
fi

echo "==> Generating Caddyfile.local (HTTP, demo allowlist)"
APP_HOST=localhost TOOLKIT_LOCAL=1 python3 "$ROOT/scripts/generate-caddyfile.py" "$CADDY_LOCAL"

compose() {
  docker compose --env-file "$ENV_TOOLKIT" -f docker-compose.yml -f docker-compose.toolkit.yml "$@"
}

if [[ "$NO_UP" -eq 1 ]]; then
  echo "==> --no-up: skipped docker compose up"
  echo "    Run: docker compose --env-file .env.toolkit -f docker-compose.yml -f docker-compose.toolkit.yml up -d --build ${SERVICES[*]}"
else
  echo "==> Building and starting: ${SERVICES[*]}"
  echo "    (first run can take several minutes)"
  compose up -d --build "${SERVICES[@]}"
fi

echo
echo "────────────────────────────────────────────────────────"
echo " Toolkit ready (local HTTP)"
echo "────────────────────────────────────────────────────────"
echo "  Landing      http://localhost/"
echo "  Admin        http://admin.localhost/"
echo "  Hello Next   http://hello-nextjs.localhost/"
echo "  Hello Flask  http://hello-flask.localhost/"
echo
echo "  Admin user   ${ADMIN_USER}"
echo "  Admin pass   ${ADMIN_PASSWORD}"
echo "  (saved in    .toolkit-admin-credentials)"
echo
echo " Next:"
echo "  ./scripts/new-app.sh myapp nextjs"
echo "  docs/TOOLKIT.md"
echo "────────────────────────────────────────────────────────"

if [[ "$NO_UP" -eq 0 ]]; then
  echo "==> Smoke checks"
  ok=0
  for url in \
    "http://localhost/" \
    "http://hello-nextjs.localhost/" \
    "http://hello-flask.localhost/"
  do
    code="000"
    for _ in $(seq 1 30); do
      code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 2 --max-time 5 "$url" 2>/dev/null || true)"
      if [[ "$code" =~ ^(200|301|302|307|308|401|403)$ ]]; then
        break
      fi
      sleep 2
    done
    if [[ "$code" =~ ^(200|301|302|307|308|401|403)$ ]]; then
      echo "  OK  $code  $url"
      ok=$((ok + 1))
    else
      echo "  …  $code  $url  (still starting — check: docker compose -f docker-compose.yml -f docker-compose.toolkit.yml ps)"
    fi
  done
  # Admin is behind basic auth — 401 means the edge is up
  admin_code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 2 --max-time 5 "http://admin.localhost/" 2>/dev/null || true)"
  if [[ "$admin_code" =~ ^(200|401|403)$ ]]; then
    echo "  OK  $admin_code  http://admin.localhost/  (basic auth)"
  else
    echo "  …  $admin_code  http://admin.localhost/  (still starting)"
  fi
fi
