#!/usr/bin/env python3
"""Generate docker-compose app service blocks from manifests.

Usage:
  python3 scripts/generate-compose.py [--output FILE] [--apps id1 id2 ...]
  python3 scripts/generate-compose.py   # discover all apps from manifests

If --apps is given, only those app IDs are emitted. Otherwise all discovered
apps (with manifest.json) are included. Use with docker-compose:
  docker compose -f docker-compose.yml -f docker-compose.apps.yml up -d

Scale: at 100s–1000s of apps, keep docker-compose.yml as base (caddy, admin,
anchor, happypath) and generate app blocks so no manual edits needed per app.
"""
import argparse
import json
import os
import sys

script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(script_dir)

# Services that stay in base docker-compose.yml (multi-service or special config)
SKIP_IDS = {"admin", "anchor", "caddy"}


def manifest_dirs():
    skip_top = {"scripts", "apps", "products", "internal", "node_modules"}
    for entry in os.listdir(repo_root):
        if entry.startswith(".") or entry in skip_top:
            continue
        path = os.path.join(repo_root, entry)
        if os.path.isdir(path):
            yield entry, path
    for root_name in ("products", "internal"):
        base = os.path.join(repo_root, root_name)
        if not os.path.isdir(base):
            continue
        stack = [(base, root_name)]
        while stack:
            dirpath, rel = stack.pop()
            for name in os.listdir(dirpath):
                if name.startswith(".") or name == "node_modules":
                    continue
                sub = os.path.join(dirpath, name)
                rel_sub = f"{rel}/{name}"
                if not os.path.isdir(sub):
                    continue
                if os.path.isfile(os.path.join(sub, "manifest.json")):
                    yield rel_sub.replace("\\", "/"), sub
                # Keep traversing so nested apps under manifest-bearing parents
                # are still discovered for generated compose blocks.
                stack.append((sub, rel_sub))


def discover_apps(app_ids_filter=None):
    """Yield (app_id, docker_service, internal_port, memory_limit, env_keys)."""
    for rel_dir, abs_path in manifest_dirs():
        manifest_path = os.path.join(abs_path, "manifest.json")
        if not os.path.isfile(manifest_path):
            continue
        try:
            with open(manifest_path) as f:
                m = json.load(f)
        except Exception:
            continue
        app_id = m.get("id")
        if not app_id or app_id in SKIP_IDS:
            continue
        if app_ids_filter is not None and app_id not in app_ids_filter:
            continue
        docker_svc = m.get("docker_service", app_id)
        internal_port = m.get("internal_port", 3000)
        memory = m.get("memory_limit", "256m")
        env_keys = [v["key"] for v in m.get("env_vars") or []]
        yield app_id, docker_svc, internal_port, memory, env_keys


def yaml_escape(s):
    if ":" in s or "#" in s or "\n" in s:
        return json.dumps(s)
    return s


def emit_yaml(app_id, docker_svc, internal_port, memory, env_keys, out):
    image = f"216labs/{docker_svc}:latest"
    svc_key = f'"{docker_svc}"' if docker_svc[0].isdigit() else docker_svc
    out.append(f"  # ── {app_id} (generated from manifest) ──")
    out.append(f"  {svc_key}:")
    out.append(f"    image: {image}")
    out.append("    restart: unless-stopped")
    out.append("    environment:")
    out.append(f"      - PORT={internal_port}")
    out.append("      - NODE_ENV=production")
    for key in env_keys:
        out.append(f"      - {key}=${{{key}:-}}")
    out.append("    expose:")
    out.append(f"      - \"{internal_port}\"")
    out.append(f"    mem_limit: {memory}")
    out.append("")


def main():
    ap = argparse.ArgumentParser(description="Generate docker-compose app blocks from manifests")
    ap.add_argument("--output", "-o", default=None, help="Output file (default: stdout)")
    ap.add_argument("--apps", nargs="*", default=None, help="App IDs to include (default: all discovered)")
    args = ap.parse_args()

    app_ids_filter = None
    if args.apps:
        app_ids_filter = set(args.apps)

    lines = [
        "# 216labs — app services (AUTO-GENERATED by scripts/generate-compose.py)",
        "# Use: docker compose -f docker-compose.yml -f docker-compose.apps.yml up -d",
        "",
        "services:",
    ]
    count = 0
    for app_id, docker_svc, internal_port, memory, env_keys in discover_apps(app_ids_filter):
        emit_yaml(app_id, docker_svc, internal_port, memory, env_keys, lines)
        count += 1

    out_text = "\n".join(lines) + "\n"
    if args.output:
        with open(args.output, "w") as f:
            f.write(out_text)
        print(f"Generated {args.output} ({count} services)", file=sys.stderr)
    else:
        print(out_text)


if __name__ == "__main__":
    main()
