#!/usr/bin/env python3
"""Generate Caddyfile from app manifests.

Usage:
  python3 scripts/generate-caddyfile.py [output_path]

Reads all manifest.json files in the repo root and generates a Caddyfile.
Special cases (admin with basic auth, anchor with path routing) are hardcoded.
All other apps get a standard subdomain reverse_proxy block.

Set APP_HOST env var to change the domain (default: agimemes.com).
"""
import sys
import json
import os

script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(script_dir)

domain = os.environ.get("APP_HOST", "agimemes.com")
output = sys.argv[1] if len(sys.argv) > 1 else os.path.join(repo_root, "Caddyfile")

lines = [
    "# 216labs — Caddy reverse proxy (subdomain-based routing)",
    "# AUTO-GENERATED by scripts/generate-caddyfile.py — do not edit manually",
    "#",
    f"# Each app is served at {{id}}.{domain} — Caddy auto-provisions",
    "# HTTPS certificates via Let's Encrypt.",
    "",
    f"admin.{domain} {{",
    "\tbasicauth {",
    "\t\t{env.ADMIN_USER} {env.ADMIN_PASSWORD_HASH}",
    "\t}",
    "\treverse_proxy admin:3000",
    "}",
    "",
    f"anchor.{domain} {{",
    "\thandle /api/* {",
    "\t\treverse_proxy anchor-api:8000",
    "\t}",
    "\thandle {",
    "\t\treverse_proxy anchor-web:80",
    "\t}",
    "}",
    "",
]

skip_ids = {"admin", "anchor"}
entries = []

for entry in os.listdir(repo_root):
    manifest_path = os.path.join(repo_root, entry, "manifest.json")
    if not os.path.isfile(manifest_path):
        continue
    try:
        with open(manifest_path) as f:
            m = json.load(f)
        app_id = m.get("id")
        if not app_id or app_id in skip_ids:
            continue
        docker_svc = m.get("docker_service", app_id)
        internal_port = m.get("internal_port", 3000)
        entries.append((app_id, docker_svc, internal_port))
    except Exception as e:
        print(f"Warning: could not read {manifest_path}: {e}", file=sys.stderr)

entries.sort(key=lambda x: x[0])

for app_id, docker_svc, port in entries:
    lines += [
        f"{app_id}.{domain} {{",
        f"\treverse_proxy {docker_svc}:{port}",
        "}",
        "",
    ]

with open(output, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {output} ({len(entries)} app entries + admin + anchor)")
