#!/usr/bin/env python3
"""Generate Caddyfile from app manifests.

Usage:
  python3 scripts/generate-caddyfile.py [output_path]

Reads all manifest.json files in the repo root and generates a Caddyfile.
Special cases (admin with basic auth, anchor with path routing) are hardcoded.
All other apps get a standard subdomain reverse_proxy block.

Set APP_HOST env var to change the domain (default: 6cubed.app).
"""
import sys
import json
import os
from urllib.parse import quote

script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(script_dir)

domain = os.environ.get("APP_HOST", "6cubed.app")
output = sys.argv[1] if len(sys.argv) > 1 else os.path.join(repo_root, "Caddyfile")

lines = [
    "# 216labs — Caddy reverse proxy (subdomain-based routing)",
    "# AUTO-GENERATED by scripts/generate-caddyfile.py — do not edit manually",
    "#",
    f"# Each app is served at {{id}}.{domain} — Caddy auto-provisions",
    "# HTTPS certificates via Let's Encrypt.",
    "",
    f"admin.{domain} {{",
    "\tbasicauth {",
    "\t\t{env.ADMIN_USER} {env.ADMIN_PASSWORD_HASH}",
    "\t}",
    "\treverse_proxy admin:3000",
    "}",
    "",
    f"anchor.{domain} {{",
    "\thandle /api/* {",
    "\t\treverse_proxy anchor-api:8000",
    "\t}",
    "\thandle {",
    "\t\treverse_proxy anchor-web:80",
    "\t}",
    "}",
    "",
]

skip_ids = {"admin", "anchor"}
entries = []
root_domain_app = None  # (docker_svc, port) for 6cubed.app + www.6cubed.app

def manifest_dirs():
    skip_top = {"scripts", "apps", "products", "internal", "node_modules"}
    for entry in os.listdir(repo_root):
        if entry.startswith(".") or entry in skip_top:
            continue
        path = os.path.join(repo_root, entry)
        if os.path.isdir(path):
            yield path
    for root_name in ("products", "internal"):
        base = os.path.join(repo_root, root_name)
        if not os.path.isdir(base):
            continue
        stack = [base]
        while stack:
            dirpath = stack.pop()
            for name in os.listdir(dirpath):
                if name.startswith(".") or name == "node_modules":
                    continue
                sub = os.path.join(dirpath, name)
                if not os.path.isdir(sub):
                    continue
                if os.path.isfile(os.path.join(sub, "manifest.json")):
                    yield sub
                # Keep traversing so nested apps (e.g. internal/admin/groundtruth)
                # are not skipped when a parent directory also has a manifest.
                stack.append(sub)


for dir_path in manifest_dirs():
    manifest_path = os.path.join(dir_path, "manifest.json")
    if not os.path.isfile(manifest_path):
        continue
    try:
        with open(manifest_path) as f:
            m = json.load(f)
        app_id = m.get("id")
        if not app_id or app_id in skip_ids:
            continue
        docker_svc = m.get("docker_service", app_id)
        internal_port = m.get("internal_port", 3000)
        if m.get("root_domain"):
            root_domain_app = (docker_svc, internal_port)
        entries.append((app_id, docker_svc, internal_port))
    except Exception as e:
        print(f"Warning: could not read {manifest_path}: {e}", file=sys.stderr)

entries.sort(key=lambda x: x[0])

# Root domain (6cubed.app + www.6cubed.app) → landing app
if root_domain_app:
    svc, port = root_domain_app
    lines += [
        f"{domain} {{",
        f"\treverse_proxy {svc}:{port}",
        "}",
        "",
        f"www.{domain} {{",
        f"\treverse_proxy {svc}:{port}",
        "}",
        "",
    ]

# On cold upstream (502/503/504), send users to Activator warmup so docker compose can start the app.
# Skip activator itself and manifests with internal_port 0 (no HTTP upstream).
for app_id, docker_svc, port in entries:
    try:
        p = int(port)
    except (TypeError, ValueError):
        p = 0
    use_warmup = app_id != "activator" and p > 0
    if use_warmup:
        dest_enc = quote(f"https://{app_id}.{domain}", safe="")
        warm = f"https://activator.{domain}/warmup?app={app_id}&dest={dest_enc}"
        # Upstream 502/503/504: handle_response (reverse_proxy does not use handle_errors for these).
        # Dial / gateway failures: handle_errors with same redirect.
        lines += [
            f"{app_id}.{domain} {{",
            f"\treverse_proxy {docker_svc}:{port} {{",
            "\t\t@cold status 502 503 504",
            "\t\thandle_response @cold {",
            f'\t\t\tredir "{warm}" 302',
            "\t\t}",
            "\t}",
            "\thandle_errors {",
            "\t\t@dial expression `{err.status_code} == 502 || {err.status_code} == 503 || {err.status_code} == 504`",
            "\t\thandle @dial {",
            f'\t\t\tredir "{warm}" 302',
            "\t\t}",
            "\t}",
            "}",
            "",
        ]
    else:
        lines += [
            f"{app_id}.{domain} {{",
            f"\treverse_proxy {docker_svc}:{port}",
            "}",
            "",
        ]

# Alias domains for common app-name typos. Keep minimal and explicit.
alias_redirects = {
    f"zurichrunningclubs.{domain}": f"https://zurichrunclubs.{domain}",
}
for alias_host, canonical_url in alias_redirects.items():
    lines += [
        f"{alias_host} {{",
        f"\tredir {canonical_url} 302",
        "}",
        "",
    ]

with open(output, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {output} ({len(entries)} app entries + admin + anchor)")
