#!/usr/bin/env python3
"""Generate Caddyfile from app manifests.

Usage:
  python3 scripts/generate-caddyfile.py [output_path]

Reads all manifest.json files in the repo root and generates a Caddyfile.
Special cases (admin with basic auth, anchor with path routing) are hardcoded.
All other apps get a standard subdomain reverse_proxy block.

Set APP_HOST env var to change the domain (default: 6cubed.app).

Local / toolkit mode (APP_HOST=localhost, or TOOLKIT_LOCAL=1):
  - Site blocks use http:// (no Let's Encrypt)
  - Warmup redirects use http://
  - Only a small allowlist of apps is routed (override with CADDY_APP_IDS=id1,id2,…)
"""
import sys
import json
import os
from urllib.parse import quote

script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(script_dir)

domain = os.environ.get("APP_HOST", "6cubed.app")
output = sys.argv[1] if len(sys.argv) > 1 else os.path.join(repo_root, "Caddyfile")

toolkit_flag = os.environ.get("TOOLKIT_LOCAL", "").strip().lower() in ("1", "true", "yes", "on")
local_mode = toolkit_flag or domain in ("localhost", "127.0.0.1", "local.test")
scheme = "http" if local_mode else "https"
# Caddy: prefix site address with http:// to disable automatic HTTPS / ACME.
site = (lambda host: f"http://{host}") if local_mode else (lambda host: host)


def warmup_redir(app_id: str, dest_host: str) -> str:
    """Activator URL. Caddy appends {http.request.uri.path} so deep links survive cold start."""
    dest_enc = quote(f"{scheme}://{dest_host}", safe="")
    return (
        f"{scheme}://activator.{domain}/warmup?app={app_id}"
        f"&dest={dest_enc}{{http.request.uri.path}}"
    )

# Default local allowlist keeps Activator from cold-starting the whole portfolio.
DEFAULT_LOCAL_APP_IDS = {"landing", "hello-nextjs", "hello-flask", "activator"}
caddy_app_ids_env = os.environ.get("CADDY_APP_IDS", "").strip()
if caddy_app_ids_env:
    allowlist = {x.strip() for x in caddy_app_ids_env.split(",") if x.strip()}
elif local_mode:
    allowlist = set(DEFAULT_LOCAL_APP_IDS)
else:
    allowlist = None  # all manifests

# One shared JSON access log (Docker volume /var/log/caddy) ingested by cron-runner → 216labs.db.edge_visitor_day
ACCESS_LOG_BLOCK = [
    "\t# JSON access log for edge visitor rollup (cron-runner job edge-visitor-rollup)",
    "\tlog {",
    "\t\toutput file /var/log/caddy/access.log {",
    "\t\t\troll_size 100mb",
    "\t\t\troll_keep 14",
    "\t\t}",
    "\t\tformat json",
    "\t}",
]

lines = [
    "# 216labs — Caddy reverse proxy (subdomain-based routing)",
    "# AUTO-GENERATED by scripts/generate-caddyfile.py — do not edit manually",
    "#",
    f"# Each app is served at {{id}}.{domain} — "
    + ("HTTP only (toolkit local)." if local_mode else "Caddy auto-provisions HTTPS via Let's Encrypt."),
    "",
    f"{site(f'admin.{domain}')} {{",
    *ACCESS_LOG_BLOCK,
    "\thandle /api/public/* {",
    "\t\treverse_proxy admin:3000",
    "\t}",
    "\thandle {",
    "\t\tbasic_auth {",
    "\t\t\t{env.ADMIN_USER} {env.ADMIN_PASSWORD_HASH}",
    "\t\t}",
    "\t\treverse_proxy admin:3000",
    "\t}",
    "}",
    "",
]

# Anchor only in full (non-local) Caddyfiles — not part of the toolkit demo stack.
if allowlist is None or "anchor" in allowlist:
    lines += [
        f"{site(f'anchor.{domain}')} {{",
        *ACCESS_LOG_BLOCK,
        "\thandle /api/* {",
        "\t\treverse_proxy anchor-api:8000",
        "\t}",
        "\thandle {",
        "\t\treverse_proxy anchor-web:80",
        "\t}",
        "}",
        "",
    ]

skip_ids = {"admin", "anchor"}
entries = []
root_domain_app = None  # (docker_svc, port) for apex + www


def manifest_dirs():
    skip_top = {"scripts", "apps", "products", "internal", "node_modules"}
    for entry in os.listdir(repo_root):
        if entry.startswith(".") or entry in skip_top:
            continue
        path = os.path.join(repo_root, entry)
        if os.path.isdir(path):
            yield path
    for root_name in ("products", "internal"):
        base = os.path.join(repo_root, root_name)
        if not os.path.isdir(base):
            continue
        stack = [base]
        while stack:
            dirpath = stack.pop()
            try:
                names = os.listdir(dirpath)
            except OSError as e:
                print(f"Warning: skip {dirpath}: {e}", file=sys.stderr)
                continue
            for name in names:
                if name.startswith(".") or name in ("node_modules", "__pycache__", ".venv", "venv", "dist"):
                    continue
                sub = os.path.join(dirpath, name)
                if not os.path.isdir(sub):
                    continue
                if os.path.isfile(os.path.join(sub, "manifest.json")):
                    yield sub
                # Keep traversing so nested apps (e.g. internal/admin/groundtruth)
                # are not skipped when a parent directory also has a manifest.
                stack.append(sub)


for dir_path in manifest_dirs():
    manifest_path = os.path.join(dir_path, "manifest.json")
    if not os.path.isfile(manifest_path):
        continue
    try:
        with open(manifest_path) as f:
            m = json.load(f)
        app_id = m.get("id")
        if not app_id or app_id in skip_ids:
            continue
        if allowlist is not None and app_id not in allowlist:
            continue
        docker_svc = m.get("docker_service", app_id)
        internal_port = m.get("internal_port", 3000)
        if m.get("root_domain"):
            root_domain_app = (docker_svc, internal_port)
        entries.append((app_id, docker_svc, internal_port))
    except Exception as e:
        print(f"Warning: could not read {manifest_path}: {e}", file=sys.stderr)

entries.sort(key=lambda x: x[0])

# Root domain → landing app (with Activator warmup on cold upstream)
if root_domain_app:
    svc, port = root_domain_app
    try:
        rp = int(port)
    except (TypeError, ValueError):
        rp = 0
    if rp > 0:
        for host in (domain, f"www.{domain}"):
            warm = warmup_redir(svc, host)
            lines += [
                f"{site(host)} {{",
                *ACCESS_LOG_BLOCK,
                "\thandle /api/* {",
                f"\t\treverse_proxy {svc}:{port}",
                "\t}",
                "\thandle /healthz {",
                f"\t\treverse_proxy {svc}:{port}",
                "\t}",
                f"\treverse_proxy {svc}:{port} {{",
                "\t\t@cold status 502 503 504",
                "\t\thandle_response @cold {",
                f'\t\t\tredir "{warm}" 302',
                "\t\t}",
                "\t}",
                "\thandle_errors {",
                "\t\t@dial expression `{err.status_code} == 0 || {err.status_code} == 502 || {err.status_code} == 503 || {err.status_code} == 504`",
                "\t\thandle @dial {",
                f'\t\t\tredir "{warm}" 302',
                "\t\t}",
                "\t}",
                "}",
                "",
            ]
    else:
        lines += [
            f"{site(domain)} {{",
            f"\treverse_proxy {svc}:{port}",
            "}",
            "",
            f"{site(f'www.{domain}')} {{",
            f"\treverse_proxy {svc}:{port}",
            "}",
            "",
        ]

# On cold upstream (502/503/504), send users to Activator warmup so docker compose can start the app.
# Skip activator itself and manifests with internal_port 0 (no HTTP upstream).
for app_id, docker_svc, port in entries:
    try:
        p = int(port)
    except (TypeError, ValueError):
        p = 0
    use_warmup = app_id != "activator" and p > 0
    if use_warmup:
        warm = warmup_redir(app_id, f"{app_id}.{domain}")
        # Upstream 502/503/504: handle_response (response came back from upstream).
        # Dial / DNS / no-backend failures: handle_errors — some Caddy builds use status 0 for dial errors.
        # Do not use a catch-all handle_errors: app 4xx/5xx responses must not redirect to warmup.
        # /api/* and /healthz skip Activator warmup so probes and webhooks get JSON/errors, not 302 HTML.
        lines += [
            f"{site(f'{app_id}.{domain}')} {{",
            "\thandle /api/* {",
            f"\t\treverse_proxy {docker_svc}:{port}",
            "\t}",
            "\thandle /healthz {",
            f"\t\treverse_proxy {docker_svc}:{port}",
            "\t}",
            f"\treverse_proxy {docker_svc}:{port} {{",
            "\t\t@cold status 502 503 504",
            "\t\thandle_response @cold {",
            f'\t\t\tredir "{warm}" 302',
            "\t\t}",
            "\t}",
            "\thandle_errors {",
            "\t\t@dial expression `{err.status_code} == 0 || {err.status_code} == 502 || {err.status_code} == 503 || {err.status_code} == 504`",
            "\t\thandle @dial {",
            f'\t\t\tredir "{warm}" 302',
            "\t\t}",
            "\t}",
            "}",
            "",
        ]
    else:
        lines += [
            f"{site(f'{app_id}.{domain}')} {{",
            f"\treverse_proxy {docker_svc}:{port}",
            "}",
            "",
        ]

# Alias domains for common app-name typos. Keep minimal and explicit.
if not local_mode:
    alias_redirects = {
        f"zurichrunningclubs.{domain}": f"https://zurichrunclubs.{domain}",
    }
    for alias_host, canonical_url in alias_redirects.items():
        lines += [
            f"{site(alias_host)} {{",
            *ACCESS_LOG_BLOCK,
            f"\tredir {canonical_url} 302",
            "}",
            "",
        ]

with open(output, "w") as f:
    f.write("\n".join(lines) + "\n")

mode = "local/toolkit" if local_mode else "production"
print(f"Generated {output} ({len(entries)} app entries + admin; mode={mode})")
